# Generated by Django 5.1.2 on 2024-12-26 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=100)),
                ('passwd', models.CharField(max_length=129)),
                ('pubkey', models.CharField(max_length=100)),
                ('privkey', models.CharField(max_length=100)),
            ],
        ),
    ]
