# Generated by Django 5.1.3 on 2024-12-31 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='iv',
            field=models.BinaryField(default=b''),
        ),
        migrations.AddField(
            model_name='usuario',
            name='salt_passwd',
            field=models.BinaryField(default=b''),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='privkey',
            field=models.BinaryField(default=b''),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='pubkey',
            field=models.CharField(max_length=215),
        ),
    ]
