# Generated by Django 4.2.16 on 2025-01-06 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_usuario_iv_usuario_salt_passwd_alter_usuario_privkey_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='date_expire_key',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
